### PR TITLE
feat(demo): add react-instantsearch

### PR DESCRIPTION
**Pull request by mthuret**
Implementation of the instant search demo using React InstantSearch. You can see a live version here: http://elite-cord.surge.sh/

Some comments:

* I replaced the button that was clearing the facets and the query by our <ClearAll/> widget that only clear the facets. We probably need to add another widget on the RIS side. 
* I used the [rc-slider](https://github.com/react-component/slider) component for the range. There's no built-in range with RIS. You need to use a connector for that.
* The SFFV searchbox placeholder can't be changed. I added a bug on RIS, this will be fixed.

### CODE REVIEW

**Comment by seafoox** [comment]
Nice pull request @mthuret 
Are you thinking to give to the implementation the same look and feel as what has been done on the InstantSearch.js demo?

**Comment by seafoox** [comment]
@bobylito What do we do in the InstantSearch.js demo when there is a active facet that matches the search query? Do we display it part of the list or not?

image

**Comment by bobylito** [comment]
@seafoox here are my answers ;)

> What do we do in the InstantSearch.js demo when there is a active facet that matches the search query? Do we display it part of the list or not?

Yes.

> When selecting a facet value, does that one should stick to the top of the list when there is not search query?

I'm not super sure about to understand based on the GIF. I only see a weird thing with insignia. I checked with @mthuret and it looks like a bug :)

**Comment by bobylito** [comment]
@mthuret the magnifying glass icon is missing. 🎶 CSS 🎶

**Comment by seafoox** [comment]
Thanks @bobylito 
Regarding the look'n'feel, do we want 
- to add magnifying glass icon
- to add cross button when queryLength > 0, in order to delete the current query
- to replace “No matching brand” with “No results”
- to replace the current highlighting style with something more `font-weight: bold`
What do you think?

Otherwise, there seems to be a margin bug when there is no results: margin bottom is then too small.

**Comment by bobylito** [comment]
> to replace “No matching brand” with “No results”

`No matching brand` is consistent with specifying a placeholder that is precise, no?
Here I would also suggest to use a font size consistent with the size used with items (13px) , and add some padding (5px 0 20px 0).

**Comment by seafoox** [comment]
@LucasC do you think it's better to display `No matching brand` or `No result`?

**Comment by LucasC** [comment]
No matching brand 👍 But as @bobylito said, with a more consistent font size.

**Comment by mthuret** [comment]
I updated the PR with your feedbacks and you can reuse the surge link to see them.

There still a bug with the refinement list SFFV sorting values but as soon as we release another RIS version with the fix, it will be ok. 

@seafoox: can you be more precise on what you mean by "Are you thinking to give to the implementation the same look and feel as what has been done on the InstantSearch.js demo?" ?  Was it concerning the SFFV or do you have other things in mind?

**Comment by seafoox** [comment]
Looks great @mthuret.

> Are you thinking to give to the implementation the same look and feel as what has been done on the InstantSearch.js demo?

Yes, was talking about the SFFV widget look'n'feel. But I think it looks the same now that you've made all those updates.

There might be one thing missing: the X to clear the current search query. Is that already under your radar?

**Comment by mthuret** [comment]
@seafoox: the X only appear when the query is not empty. Do you have trouble seeing it?

**Comment by seafoox** [comment]
that's perfect @mthuret

**Comment by Haroenv** [comment]
https://github.com/algolia/examples/pull/34#issuecomment-273488862 is fixed in https://github.com/algolia/instantsearch.js/pull/1970 (v3.2.0) @seafoox

**Pull request merged**
