### PR TITLE
feat(is-demo-instantsearch.js): Add SFFV

### PR DESCRIPTION
**Pull request by bobylito**
Adds search for facet values in the instantsearch.js flavoured instantsearch-demo. Very few changes, thanks to instantsearch.js. However I always like an exterior eye @seafoox @pixelastic @kokliKo 

The live version is [here](http://unequaled-lift.surge.sh/).

### CODE REVIEW

**Comment by pixelastic** [comment]
Nice job! Really improves usability.

A few remarks:

image
I would add a bit of padding around the "No results" and maybe change it to "No matching brands" or something more in context.

Seems like I cannot search for `™`, I gives no results while I expect to have `Insignia™`. I know it's an edge case but surprising.

I still tried to navigate with the keyboard :)

**Comment by bobylito** [comment]
Thanks for the review @pixelastic I will provide some love to the no results :)

**Comment by seafoox** [comment]
@bobylito can you confirm that you made a pass polishing the UI?

**Comment by seafoox** [comment]
As we are polishing it, could look even better with
- a bit more bottom margin on the input
- default font size on the "No result" message

And also to replace` "No results"` by `“No matching brand”` to make it consistent with the other implementations

**Pull request merged**
