### PR TITLE
docs(instant-search): show off the demo right away

### PR DESCRIPTION
**Pull request by vvo**
I was looking for the underlying live demo and had to scroll too much I feel to find this information

### CODE REVIEW

**Comment by olance** [comment]
@vvo thanks!
About the eslint errors: how can I specify that `instantsearch` **is** defined as a global function?

**Comment by dustincoates** [comment]
@olance Check out the lint PR, there are a number of examples there.

**Comment by olance** [comment]
:)
OK :+1:

**Comment by dustincoates** [comment]
@olance Here it is in short:
```
/* global instantsearch */
```

**Comment by vvo** [comment]
I did it in master sorry..

**Pull request merged**
